//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Developer
    {
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Highest_Qualification { get; set; }
        public Nullable<int> Experience_Year { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Skills { get; set; }
        public string Photo { get; set; }
        public string Address { get; set; }
        public System.DateTime Saving_Date { get; set; }
    }
}
