//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForgotPassword
    {
        public int ForgotId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<bool> Issued { get; set; }
        public Nullable<System.DateTime> Date_TIme { get; set; }
    }
}
