//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techwork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Techwork_DBEntities : DbContext
    {
        public Techwork_DBEntities()
            : base("name=Techwork_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client_Table> Client_Table { get; set; }
        public virtual DbSet<Developer> Developers { get; set; }
        public virtual DbSet<Enquiry> Enquiries { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PostedProject> PostedProjects { get; set; }
        public virtual DbSet<RequestedProject> RequestedProjects { get; set; }
        public virtual DbSet<UploadProject> UploadProjects { get; set; }
        public virtual DbSet<ForgotPassword> ForgotPasswords { get; set; }
    }
}
