//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostedProject
    {
        public int ProjectId { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<decimal> MaximumCost { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string DescriptionOfProject { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> Posted_On { get; set; }
        public string PostedBy { get; set; }
    }
}
