//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadProject
    {
        public int UploadId { get; set; }
        public string UploadedBy { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> Uploaded_On { get; set; }
        public string thisclient { get; set; }
    }
}
